#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point
#       to that shell before running this script, e.g.:
#           SHELL=/usr/bin/ksh ./gradlew
#
#   (2) The script point to a Java installation. If you get an error like:
#           JAVA_HOME is not set
#       then you need to set the JAVA_HOME environment variable.
#
##############################################################################

APP_NAME="Gradle"
APP_BASE_NAME=`basename "$0"`

# Use the maximum available file descriptors, if supported.
ulimit -n 4096 2>/dev/null || true

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD="$JAVA_HOME/jre/sh/java"
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi
    if [ ! -x "$JAVACMD" ] ; then
        echo "Error: JAVA_HOME is set to an invalid directory: $JAVA_HOME" >&2
        exit 1
    fi
else
    JAVACMD="java"
    which java >/dev/null 2>&1 || echo "Error: JAVA_HOME not found in PATH" >&2
fi

# Increase the maximum file descriptors if we can.
if [ "$(ulimit -n)" -lt 4096 ]; then
    ulimit -n 4096 2>/dev/null || true
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * the classpath 'gradle-launcher.jar'

set -- \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Use "xargs" to parse quoted args.
# The use of "xargs" is required for proper handling of quoted arguments in a POSIX shell.
# It also handles the case of arguments with spaces.
eval "set -- $(
    printf '%s\n' "$@" | xargs -n1 -I{} printf "'%s' " {} |
    sed -e "s/^ *//" -e "s/ *$//"
)"

exec "$JAVACMD" "$@"
